--create account--
--dummy databse creation--
CREATE TABLE IF NOT EXISTS ACCOUNTS(
    ACCOUNTNUMBER INTEGER PRIMARY KEY NOT NULL AUTOINCREMENT,
    CUSTOMERNAME VARCHAR(255) NOT NULL,
    ACCOUNTTYPE TEXT CHECK(ACCOUNTTYPE IN('SAVINGS','CURRENT')),
    BALANCE REAL NOT NULL DEFAULT 0,
    ISACTIVE INTEGER NOT NULL DEFAULT 1,--1 FOR ACTIVE 0 FOR NON ACTIVE--
    CREATEDAT TEXT DEFAULT(DATETIME('NOW'))
);

--CREATE TRANSACTION--
CREATE TABLE IF NOT EXISTS TRANSACTIONS(
    ID INTEGER PRIMARY KEY NOT NULL,
    ACCOUNTNUMBER INTEGER NOT NULL,
    TYPE TEXT CHECK(ACCOUNTTYPE IN('DEPOSIT'.'WITHDRAW','TRANSFER')),
    AMOUNT REAL,
    DESCRIPTION VARCHAR(255),
    TIMESTAMP TEXT DEFAULT(DATETIME('NOW')),
    BALANCEAFTER REAL NOT NULL,
    FOREIGN KEY (ACCOUNTNUMBER) REFERENCES ACCOUNTS(ACCOUNTNUMBER)
);